/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package instituto;

import com.formdev.flatlaf.FlatDarculaLaf;
import com.formdev.flatlaf.FlatDarkLaf;
import com.formdev.flatlaf.FlatIntelliJLaf;
import com.formdev.flatlaf.FlatLaf;
import com.formdev.flatlaf.FlatLightLaf;
import com.formdev.flatlaf.intellijthemes.FlatCyanLightIJTheme;
import instituto.busquedas.Busqueda;
import instituto.aulas.A104;
import instituto.aulas.A301;
import instituto.aulas.A302;
import instituto.aulas.A102;
import instituto.aulas.A103;
import instituto.aulas.A201;
import instituto.aulas.A303;
import instituto.aulas.A106;
import instituto.aulas.A101;
import instituto.aulas.A202;
import instituto.aulas.A105;
import instituto.aulas.Laboratorio;
import instituto.perfil.VerArchivos;
import instituto.perfil.VerPerfil;
import java.awt.BorderLayout;
import java.awt.EventQueue;
import login.Login;
import java.sql.*;




/**
 *
 * @author ivan.castellano
 */
public class Principal extends javax.swing.JFrame {

    private int idProfesor;
    private int idRol;
    private String nombre;
    private String apellido;
    private String correo;
    public Principal(int idProfesor) {
        this.idProfesor = idProfesor;
        initComponents();
        mostrarDatosProfesor();
        restringirFuncionalidadesSegunRol();
    }
        private void mostrarDatosProfesor() {
        try {
            // Conectar a la base de datos
            Connection connection = DriverManager.getConnection("jdbc:hsqldb:hsql://localhost/", "SA", "");
            Statement statement = connection.createStatement();

            // Consultar los datos del profesor
            String query = "SELECT * FROM instituto.profesores WHERE \"ID profesor\" = " + idProfesor;
            ResultSet resultSet = statement.executeQuery(query);

            if (resultSet.next()) {
                String nombre = resultSet.getString("NOMBRE");
                String apellido = resultSet.getString("APELLIDO");
                String correo = resultSet.getString("CORREOELECTRONICO");

                // Actualizar el JLabel o cualquier otro componente con los datos del profesor
                nombre = this.nombre;
                apellido = this.apellido;
                correo = this.correo;
            }

            resultSet.close();
            statement.close();
            connection.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    private void restringirFuncionalidadesSegunRol() {
        try {
            // Conectar a la base de datos
            Connection connection = DriverManager.getConnection("jdbc:hsqldb:hsql://localhost/", "SA", "");
            Statement statement = connection.createStatement();

            // Consultar los roles del profesor
            String query = "SELECT ID_ROL FROM instituto.asignacion_roles WHERE ID_PROFESOR = " + idProfesor;
            ResultSet resultSet = statement.executeQuery(query);

            while (resultSet.next()) {
                int idRol = resultSet.getInt("ID_ROL");
                idRol = this.idRol;
            }

            resultSet.close();
            statement.close();
            connection.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jTextField10 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jTextField19 = new javax.swing.JTextField();
        jTextField20 = new javax.swing.JTextField();
        jTextField21 = new javax.swing.JTextField();
        jTextField22 = new javax.swing.JTextField();
        jTextField23 = new javax.swing.JTextField();
        jTextField24 = new javax.swing.JTextField();
        jTextField25 = new javax.swing.JTextField();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jPanel6 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        A101 = new javax.swing.JButton();
        A103 = new javax.swing.JButton();
        A102 = new javax.swing.JButton();
        baños = new javax.swing.JButton();
        A106 = new javax.swing.JButton();
        laboratorio = new javax.swing.JButton();
        A104 = new javax.swing.JButton();
        A105 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        conferencias = new javax.swing.JButton();
        baños2 = new javax.swing.JButton();
        A201 = new javax.swing.JButton();
        A202 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        A301 = new javax.swing.JButton();
        reuniones = new javax.swing.JButton();
        A302 = new javax.swing.JButton();
        A303 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setText("A101");

        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField4.setText("A102");
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jTextField6.setBackground(new java.awt.Color(102, 255, 204));
        jTextField6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField6.setText("A103");
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });

        jTextField7.setBackground(new java.awt.Color(102, 255, 204));
        jTextField7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField7.setText("A103");
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });

        jTextField8.setBackground(new java.awt.Color(102, 255, 204));
        jTextField8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField8.setText("A103");
        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });

        jTextField11.setBackground(new java.awt.Color(102, 255, 204));
        jTextField11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField11.setText("A103");
        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });

        jTextField14.setBackground(new java.awt.Color(102, 255, 204));
        jTextField14.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField14.setText("A104");
        jTextField14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField14ActionPerformed(evt);
            }
        });

        jTextField16.setBackground(new java.awt.Color(102, 255, 204));
        jTextField16.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField16.setText("A105");
        jTextField16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField16ActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTextField10.setBackground(new java.awt.Color(255, 0, 0));
        jTextField10.setForeground(new java.awt.Color(255, 255, 255));
        jTextField10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField10.setText("A102");
        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });

        jTextField18.setBackground(new java.awt.Color(255, 0, 0));
        jTextField18.setForeground(new java.awt.Color(255, 255, 255));
        jTextField18.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField18.setText("A103");
        jTextField18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField18ActionPerformed(evt);
            }
        });

        jTextField19.setBackground(new java.awt.Color(0, 204, 255));
        jTextField19.setForeground(new java.awt.Color(255, 255, 255));
        jTextField19.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField19.setText("baños");
        jTextField19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField19ActionPerformed(evt);
            }
        });

        jTextField20.setBackground(new java.awt.Color(255, 0, 0));
        jTextField20.setForeground(new java.awt.Color(255, 255, 255));
        jTextField20.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField20.setText("A101");

        jTextField21.setBackground(new java.awt.Color(51, 102, 255));
        jTextField21.setForeground(new java.awt.Color(255, 255, 255));
        jTextField21.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField21.setText("laboratorio");
        jTextField21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField21ActionPerformed(evt);
            }
        });

        jTextField22.setBackground(new java.awt.Color(255, 51, 51));
        jTextField22.setForeground(new java.awt.Color(255, 255, 255));
        jTextField22.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField22.setText("A104");
        jTextField22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField22ActionPerformed(evt);
            }
        });

        jTextField23.setBackground(new java.awt.Color(255, 0, 0));
        jTextField23.setForeground(new java.awt.Color(255, 255, 255));
        jTextField23.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField23.setText("A106");
        jTextField23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField23ActionPerformed(evt);
            }
        });

        jTextField24.setBackground(new java.awt.Color(255, 0, 0));
        jTextField24.setForeground(new java.awt.Color(255, 255, 255));
        jTextField24.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField24.setText("A105");
        jTextField24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField24ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jTextField18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextField19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField22)
                    .addComponent(jTextField21)
                    .addComponent(jTextField23)
                    .addComponent(jTextField24))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jTextField20, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextField21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField18, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField22, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField19, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(jTextField24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField23, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTextField25.setBackground(new java.awt.Color(51, 102, 255));
        jTextField25.setForeground(new java.awt.Color(255, 255, 255));
        jTextField25.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField25.setText("laboratorio");
        jTextField25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField25ActionPerformed(evt);
            }
        });

        jMenuItem7.setText("jMenuItem7");

        jMenu3.setText("jMenu3");

        jMenuItem8.setText("jMenuItem8");

        jMenuItem9.setText("jMenuItem9");

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Instituto");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        setSize(new java.awt.Dimension(1000, 700));

        jPanel6.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        A101.setBackground(new java.awt.Color(239, 118, 122));
        A101.setForeground(new java.awt.Color(255, 255, 255));
        A101.setText("A101");
        A101.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A101ActionPerformed(evt);
            }
        });
        jPanel2.add(A101, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 130, 120));

        A103.setBackground(new java.awt.Color(239, 118, 122));
        A103.setForeground(new java.awt.Color(255, 255, 255));
        A103.setText("A103");
        A103.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A103ActionPerformed(evt);
            }
        });
        jPanel2.add(A103, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 242, 130, 130));

        A102.setBackground(new java.awt.Color(239, 118, 122));
        A102.setForeground(new java.awt.Color(255, 255, 255));
        A102.setText("A102");
        A102.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A102ActionPerformed(evt);
            }
        });
        jPanel2.add(A102, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 122, 130, 120));

        baños.setBackground(new java.awt.Color(51, 153, 255));
        baños.setForeground(new java.awt.Color(255, 255, 255));
        baños.setText("baños");
        jPanel2.add(baños, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 372, 130, 60));

        A106.setBackground(new java.awt.Color(239, 118, 122));
        A106.setForeground(new java.awt.Color(255, 255, 255));
        A106.setText("A106");
        A106.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A106ActionPerformed(evt);
            }
        });
        jPanel2.add(A106, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 422, 130, 100));

        laboratorio.setBackground(new java.awt.Color(51, 255, 102));
        laboratorio.setForeground(new java.awt.Color(255, 255, 255));
        laboratorio.setText("laborataorio");
        laboratorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laboratorioActionPerformed(evt);
            }
        });
        jPanel2.add(laboratorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 2, 130, 240));

        A104.setBackground(new java.awt.Color(239, 118, 122));
        A104.setForeground(new java.awt.Color(255, 255, 255));
        A104.setText("A104");
        A104.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A104ActionPerformed(evt);
            }
        });
        jPanel2.add(A104, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 242, 130, 90));

        A105.setBackground(new java.awt.Color(239, 118, 122));
        A105.setForeground(new java.awt.Color(255, 255, 255));
        A105.setText("A105");
        A105.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A105ActionPerformed(evt);
            }
        });
        jPanel2.add(A105, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 332, 130, 90));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        conferencias.setBackground(new java.awt.Color(153, 153, 153));
        conferencias.setForeground(new java.awt.Color(255, 255, 255));
        conferencias.setText("sala de conferencias");
        jPanel4.add(conferencias, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 2, 290, 60));

        baños2.setBackground(new java.awt.Color(255, 224, 51));
        baños2.setForeground(new java.awt.Color(255, 255, 255));
        baños2.setText("baños");
        jPanel4.add(baños2, new org.netbeans.lib.awtextra.AbsoluteConstraints(552, 2, 100, 60));

        A201.setBackground(new java.awt.Color(255, 224, 51));
        A201.setForeground(new java.awt.Color(255, 255, 255));
        A201.setText("A201");
        A201.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A201ActionPerformed(evt);
            }
        });
        jPanel4.add(A201, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 120, 60));

        A202.setBackground(new java.awt.Color(255, 224, 51));
        A202.setForeground(new java.awt.Color(255, 255, 255));
        A202.setText("A202");
        A202.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A202ActionPerformed(evt);
            }
        });
        jPanel4.add(A202, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 2, 140, 60));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        A301.setBackground(new java.awt.Color(125, 122, 188));
        A301.setForeground(new java.awt.Color(255, 255, 255));
        A301.setText("A301");
        A301.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A301ActionPerformed(evt);
            }
        });
        jPanel5.add(A301, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 180, 70));

        reuniones.setBackground(new java.awt.Color(153, 153, 153));
        reuniones.setForeground(new java.awt.Color(255, 255, 255));
        reuniones.setText("sala de reuniones");
        reuniones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reunionesActionPerformed(evt);
            }
        });
        jPanel5.add(reuniones, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 342, 130, 180));

        A302.setBackground(new java.awt.Color(125, 122, 188));
        A302.setForeground(new java.awt.Color(255, 255, 255));
        A302.setText("A302");
        A302.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A302ActionPerformed(evt);
            }
        });
        jPanel5.add(A302, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 2, 130, 200));

        A303.setBackground(new java.awt.Color(125, 122, 188));
        A303.setForeground(new java.awt.Color(255, 255, 255));
        A303.setText("A303");
        A303.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A303ActionPerformed(evt);
            }
        });
        jPanel5.add(A303, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 202, 130, 140));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/planta 2.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/plantas.png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/planta 2.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/plantas.png"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/plantas.png"))); // NOI18N

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/planta3.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 655, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel2))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(163, 163, 163)
                                .addComponent(jLabel3)
                                .addGap(191, 191, 191)
                                .addComponent(jLabel1)
                                .addGap(56, 56, 56))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(132, 132, 132)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 191, Short.MAX_VALUE)
                                .addComponent(jLabel5)
                                .addGap(73, 73, 73)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(20, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(70, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(36, 36, 36)
                                        .addComponent(jLabel1))
                                    .addComponent(jLabel2))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(208, 208, 208)
                                        .addComponent(jLabel8))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(114, 114, 114)
                                        .addComponent(jLabel5)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(99, 99, 99)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4)
                                .addGap(77, 77, 77))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        jPanel6.add(jPanel1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel6, java.awt.BorderLayout.CENTER);

        jMenu1.setText("Mapa");

        jMenuItem6.setText("ver");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem6);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("ver");
        jMenu2.add(jSeparator1);

        jMenuItem1.setText("datos");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("Modo");

        jMenuItem12.setText("cyan");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem12);

        jMenuItem11.setText("oscuro");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem11);

        jMenuItem10.setText("claro");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem10);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Perfil");

        jMenuItem4.setText("ver");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem4);

        jMenuItem3.setText("ver archivos");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem3);

        jMenuItem5.setText("aulas reservadas");
        jMenuItem5.setToolTipText("");
        jMenu5.add(jMenuItem5);

        jMenuItem13.setText("tus clases");
        jMenu5.add(jMenuItem13);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void jTextField14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField14ActionPerformed

    private void jTextField16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField16ActionPerformed

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void jTextField18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField18ActionPerformed

    private void jTextField19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField19ActionPerformed

    private void jTextField21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField21ActionPerformed

    private void jTextField22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField22ActionPerformed

    private void jTextField23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField23ActionPerformed

    private void jTextField24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField24ActionPerformed

    private void jTextField25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField25ActionPerformed

    private void A301ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A301ActionPerformed
        A301 a = new A301(this);
       a.setVisible(true);
       this.setEnabled(false);
    }//GEN-LAST:event_A301ActionPerformed

    private void reunionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reunionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reunionesActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        jPanel6.removeAll();
        jPanel6.setLayout(new BorderLayout());
        this.setSize(1375, 652);
        jPanel6.add(this.jPanel1);
        jPanel6.revalidate();
        jPanel6.repaint();
           
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void A101ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A101ActionPerformed
     A101 a = new A101(this);
    a.setVisible(true);
    this.setEnabled(false);
    }//GEN-LAST:event_A101ActionPerformed

    private void A102ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A102ActionPerformed
      A102 a = new A102(this);
    a.setVisible(true);
    this.setEnabled(false);
    }//GEN-LAST:event_A102ActionPerformed

    private void A103ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A103ActionPerformed
      A103 a = new A103(this);
    a.setVisible(true);
    this.setEnabled(false);
    }//GEN-LAST:event_A103ActionPerformed

    private void A104ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A104ActionPerformed
     A104 a = new A104(this);
    a.setVisible(true);
    this.setEnabled(false);
    }//GEN-LAST:event_A104ActionPerformed

    private void A105ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A105ActionPerformed
       A105 a = new A105(this);
    a.setVisible(true);
    this.setEnabled(false);
    }//GEN-LAST:event_A105ActionPerformed

    private void A106ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A106ActionPerformed
      A106 a = new A106(this);
    a.setVisible(true);
    this.setEnabled(false);
    }//GEN-LAST:event_A106ActionPerformed

    private void A201ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A201ActionPerformed
       A201 a = new A201(this);
    a.setVisible(true);
    this.setEnabled(false);
    }//GEN-LAST:event_A201ActionPerformed

    private void A202ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A202ActionPerformed
     A202 a = new A202(this);
    a.setVisible(true);
    this.setEnabled(false);
    }//GEN-LAST:event_A202ActionPerformed

    private void A302ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A302ActionPerformed
       A301 a = new A301(this);
        a.setVisible(true);
        this.setEnabled(false);
    }//GEN-LAST:event_A302ActionPerformed

    private void A303ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A303ActionPerformed
        A303 a = new A303(this);
       a.setVisible(true);
       this.setEnabled(false);
    }//GEN-LAST:event_A303ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
       EventQueue.invokeLater(new Runnable(){
                @Override
                public void run(){
                    FlatLightLaf.setup();
                    FlatLaf.updateUI();
            }
            });
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
       EventQueue.invokeLater(new Runnable(){
                @Override
                public void run(){
                    FlatDarkLaf.setup();
                    FlatLaf.updateUI();
            }
            });
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
       EventQueue.invokeLater(new Runnable(){
                @Override
                public void run(){
                    FlatCyanLightIJTheme.setup();
                    FlatLaf.updateUI();
            }
            });
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        jPanel6.removeAll();
        Busqueda pa = new Busqueda(idRol);
        jPanel6.setLayout(new BorderLayout());
        this.setSize(950, 600);
        jPanel6.add(pa, BorderLayout.CENTER);
        jPanel6.add(pa);
        jPanel6.revalidate();
        jPanel6.repaint();

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
       jPanel6.removeAll();
        VerPerfil pa = new VerPerfil(idProfesor);
        jPanel6.setLayout(new BorderLayout());
        this.setSize(560, 350);
        jPanel6.add(pa, BorderLayout.CENTER);
        jPanel6.add(pa);
        jPanel6.revalidate();
        jPanel6.repaint();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        jPanel6.removeAll();
        VerArchivos pa = new VerArchivos(idProfesor);
        jPanel6.setLayout(new BorderLayout());
        this.setSize(850, 600);
        jPanel6.add(pa, BorderLayout.CENTER);
        jPanel6.add(pa);
        jPanel6.revalidate();
        jPanel6.repaint();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void laboratorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laboratorioActionPerformed
        Laboratorio a = new Laboratorio(this);
        a.setVisible(true);
        this.setEnabled(false);
    }//GEN-LAST:event_laboratorioActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        

        //</editor-fold>

        /* Create and display the form */
          
                FlatCyanLightIJTheme.setup();
                 Login LoginFrame = new Login();
                 LoginFrame.setVisible(true);
                 LoginFrame.pack();
                 LoginFrame.setLocationRelativeTo(null);
    }
             
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton A101;
    private javax.swing.JButton A102;
    private javax.swing.JButton A103;
    private javax.swing.JButton A104;
    private javax.swing.JButton A105;
    private javax.swing.JButton A106;
    private javax.swing.JButton A201;
    private javax.swing.JButton A202;
    private javax.swing.JButton A301;
    private javax.swing.JButton A302;
    private javax.swing.JButton A303;
    private javax.swing.JButton baños;
    private javax.swing.JButton baños2;
    private javax.swing.JButton conferencias;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField25;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JButton laboratorio;
    private javax.swing.JButton reuniones;
    // End of variables declaration//GEN-END:variables
}

