/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package instituto.perfil;

import instituto.busquedas.añadir.ImageRenderer;
import instituto.busquedas.añadir.ImageRenderer2;
import java.awt.event.MouseEvent;
import java.awt.event.MouseAdapter;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
/**
 *
 * @author ivan.castellano
 */
public class AsignarRoles extends javax.swing.JPanel {

      private int rol;
      private DefaultTableModel tableModel;
      
    public AsignarRoles(int Rol) {
        this.rol = rol;
        initComponents();
        cargarAsignaciones();
        verificarProfesoresSinRol();
        
         jTable1.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                int column = jTable1.columnAtPoint(e.getPoint());
                int row = jTable1.rowAtPoint(e.getPoint());
                if (column == jTable1.getColumnCount() - 1) { // Columna de eliminación
                    int opcion = JOptionPane.showConfirmDialog(null, "¿Estás seguro de que deseas eliminar esta asignación?", "Confirmar eliminación", JOptionPane.YES_NO_OPTION);
                    if (opcion == JOptionPane.YES_OPTION) {
                        // Obtener valores de la fila seleccionada
                        String nombreProfesor = (String) tableModel.getValueAt(row, 0);
                        String nombreRol = (String) tableModel.getValueAt(row, 1);
                        // Obtener IDs correspondientes
                        int idProfesor = obtenerIdProfesor(nombreProfesor);
                        int idRol = obtenerIdRol(nombreRol);
                        if (idProfesor != -1 && idRol != -1) {
                            // Eliminar de la base de datos
                            eliminarAsignacion(idProfesor, idRol);
                            // Eliminar de la tabla
                            tableModel.removeRow(row);
                        } else {
                            JOptionPane.showMessageDialog(null, "Error al obtener el ID del profesor o del rol.");
                        }
                    }
                }
            }
        });
    }
      // Añadir el MouseListener para detectar clics en la columna de eliminación
       
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("buscar");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "profesor", "rol" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(71, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
        );
    }// </editor-fold>//GEN-END:initComponents

        private void cargarAsignaciones() {
        ImageIcon deleteIcon = new ImageIcon(getClass().getResource("/imagenes/delete.png"));

        // Limpiar la tabla antes de cargar nuevas asignaciones
        tableModel = new DefaultTableModel();
        jTable1.setModel(tableModel);
        tableModel.addColumn("Nombre Profesor");
        tableModel.addColumn("Nombre Rol");
        tableModel.addColumn("Eliminar"); // Agregar columna de "Eliminar" con imagen

        try {
            // Conectar a la base de datos
            Connection con = DriverManager.getConnection("jdbc:hsqldb:hsql://localhost/", "SA", "");

            // Consulta SQL para obtener las asignaciones de roles
            String query = "SELECT P.NOMBRE, R.NOMBRE_ROL FROM INSTITUTO.ASIGNACION_ROLES AR "
                    + "JOIN INSTITUTO.PROFESORES P ON AR.ID_PROFESOR = P.\"ID profesor\" "
                    + "JOIN INSTITUTO.ROLES R ON AR.ID_ROL = R.ID_ROL";
            PreparedStatement pst = con.prepareStatement(query);

            // Ejecutar la consulta
            ResultSet rs = pst.executeQuery();

            // Iterar sobre los resultados y agregarlos a la tabla
            while (rs.next()) {
                String nombreProfesor = rs.getString("NOMBRE");
                String nombreRol = rs.getString("NOMBRE_ROL");
                tableModel.addRow(new Object[]{nombreProfesor, nombreRol, deleteIcon});
            }

            // Centrar las celdas de todas las columnas
            DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
            centerRenderer.setHorizontalAlignment(JLabel.CENTER);
            for (int i = 0; i < jTable1.getColumnCount(); i++) {
                jTable1.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
            }

            // Configurar la columna de eliminación para mostrar el icono correctamente
            int deleteColumnIndex = tableModel.getColumnCount() - 1;
            jTable1.getColumnModel().getColumn(deleteColumnIndex).setCellRenderer(new ImageRenderer2(deleteIcon, 20));

            // Cerrar la conexión y liberar recursos
            rs.close();
            pst.close();
            con.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
            private void verificarProfesoresSinRol() {
        try {
            // Conectar a la base de datos
            Connection con = DriverManager.getConnection("jdbc:hsqldb:hsql://localhost/", "SA", "");

            // Consulta SQL para verificar profesores sin rol asignado
            String query = "SELECT P.NOMBRE FROM INSTITUTO.PROFESORES P WHERE P.\"ID profesor\" NOT IN "
                    + "(SELECT ID_PROFESOR FROM INSTITUTO.ASIGNACION_ROLES)";

            PreparedStatement pst = con.prepareStatement(query);

            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                // Hay profesores sin rol asignado, mostrar aviso
                JOptionPane.showMessageDialog(null, "¡Hay profesores sin rol asignado!", "Aviso", JOptionPane.WARNING_MESSAGE);

                // Crear instancia del JFrame para mostrar los profesores sin rol
                ProfesoresSinRol frame = new ProfesoresSinRol();
                frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                frame.setVisible(true);
                frame.setLocationRelativeTo(null); // Centrar en la pantalla
            }

            // Cerrar la conexión y liberar recursos
            rs.close();
            pst.close();
            con.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
    private int obtenerIdProfesor(String nombreProfesor) {
        int idProfesor = -1;
        try {
            // Conectar a la base de datos
            Connection con = DriverManager.getConnection("jdbc:hsqldb:hsql://localhost/", "SA", "");

            // Consulta SQL para obtener el ID del profesor
            String query = "SELECT \"ID profesor\" FROM INSTITUTO.PROFESORES WHERE NOMBRE = ?";
            PreparedStatement pst = con.prepareStatement(query);
            pst.setString(1, nombreProfesor);

            // Ejecutar la consulta
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                idProfesor = rs.getInt(1);
            }

            // Cerrar la conexión y liberar recursos
            rs.close();
            pst.close();
            con.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return idProfesor;
    }

    private int obtenerIdRol(String nombreRol) {
        int idRol = -1;
        try {
            // Conectar a la base de datos
            Connection con = DriverManager.getConnection("jdbc:hsqldb:hsql://localhost/", "SA", "");

            // Consulta SQL para obtener el ID del rol
            String query = "SELECT ID_ROL FROM INSTITUTO.ROLES WHERE NOMBRE_ROL = ?";
            PreparedStatement pst = con.prepareStatement(query);
            pst.setString(1, nombreRol);

            // Ejecutar la consulta
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                idRol = rs.getInt(1);
            }

            // Cerrar la conexión y liberar recursos
            rs.close();
            pst.close();
            con.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return idRol;
    }

    private void eliminarAsignacion(int idProfesor, int idRol) {
        try {
            // Conectar a la base de datos
            Connection con = DriverManager.getConnection("jdbc:hsqldb:hsql://localhost/", "SA", "");

            // Consulta SQL para eliminar la asignación de rol
            String query = "DELETE FROM INSTITUTO.ASIGNACION_ROLES WHERE ID_PROFESOR = ? AND ID_ROL = ?";
            PreparedStatement pst = con.prepareStatement(query);
            pst.setInt(1, idProfesor);
            pst.setInt(2, idRol);

            // Ejecutar la eliminación
            pst.executeUpdate();

            // Cerrar la conexión y liberar recursos
            pst.close();
            con.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
